### ISSUE TITLE
doesnt work if min value = 1 and current value = 1

### ISSUE THREAD

**Issue by keithics** [BalestraPatrick/ValueStepper#10]
doesn't work if min value = 1 and current value = 1

![screen shot 2017-01-24 at 9 58 18 am](https://cloud.githubusercontent.com/assets/229427/22230971/afee42de-e21b-11e6-8a8a-4f5d3d25cdd9.png)
![screen shot 2017-01-24 at 9 58 27 am](https://cloud.githubusercontent.com/assets/229427/22230972/aff3646c-e21b-11e6-91ce-19eb51f9b0a9.png)

**Comment by BalestraPatrick** [comment]
Hey! I am going to take a look at this as soon as possible. Let me know if you find the source of the bug before me 😄

**Comment by BalestraPatrick** [comment]
Are you using the `swift2.3` branch or `master`? The latter works perfectly for me.

**Comment by skibadawid** [comment]
Had the same issue, though i wasn't using attributes inspector, just programmatically setting the stepper (using pod so I guess its from master). Had code below that caused the issue:
```
self.stepper.value = 1.0
self.stepper.stepValue = 1.0
self.stepper.minimumValue = 1.0
self.stepper.maximumValue = 50.0
```
I changed the order of how I was setting up the stepper and it seemed to do the trick:
```
self.stepper.stepValue = 1.0
self.stepper.minimumValue = 1.0
self.stepper.maximumValue = 50.0
self.stepper.value = 1.0  
```
So I think you just value after you set the min/max of the stepper.

**Comment by BalestraPatrick** [comment]
I was able to reproduce the bug. I think with my last commits on master it should be fixed now! I just released a new version on CocoaPods, please let me know if that fixes it for you 👍

**Comment by BalestraPatrick** [comment]
@skibadawid Were you able to see if this issue is fixed in your case?

**Comment by skibadawid** [comment]
@BalestraPatrick yeah updated the pod and it works.

**Comment by veluloganathan** [comment]
it doesn't work if min value = 1 and current value = 1 which is set in storyboard. It works when i set in code

**Comment by BalestraPatrick** [comment]
@veluloganathan That's exactly what the example project does. I just checked it and it should work. Are you sure that the max value isn't 1? Please let me know of an example project that shows this behavior.
