### ISSUE TITLE
changing tint color of stepper doesn't update the decrease/increate layer (- / +)

### ISSUE THREAD

**Issue by skibadawid** [BalestraPatrick/ValueStepper#11]
I have put the stepper in a tableViewCell, and for testing purposes every time the cell is show, the tint color is chosen randomly so, so once they go out of view, and come back they will have new color.
<img width="373" alt="screen shot 2017-01-26 at 1 33 38 pm" src="https://cloud.githubusercontent.com/assets/6530356/22345051/986fd39a-e3cc-11e6-82f1-a9994d595af6.png">
After coming back into view.
<img width="369" alt="screen shot 2017-01-26 at 1 34 01 pm" src="https://cloud.githubusercontent.com/assets/6530356/22345054/9b1a9576-e3cc-11e6-9e65-5ac37c5eee0c.png">

fix would be to add these into func tintColorDidChange()
```
increaseLayer.strokeColor = tintColor.cgColor
decreaseLayer.strokeColor = tintColor.cgColor
```

**Comment by BalestraPatrick** [comment]
Hey @skibadawid, have you got time to open a PR for this? Let me know if you would be happy to help otherwise I will do it myself 😀

**Comment by skibadawid** [comment]
yeah of course, probably should have done that originally.

**Comment by skibadawid** [comment]
@BalestraPatrick  it seems i don't have permission to create a branch with the fix. tried it with both GitHub desktop and terminal.

**Comment by BalestraPatrick** [comment]
@skibadawid I see you have forked my repo and that's correct. You should now push to your repo the new feature in your master branch. Once that's done, create a PR in my repo based on your master branch. In this way I'll be able to merge your change right away 😄

**Comment by skibadawid** [comment]
ahhh ok. thanks for the steps, I'm still a noob with PR and stuff.

**Comment by BalestraPatrick** [comment]
Don't worry, thanks a lot for taking the time! I just merged it 🙌
