### ISSUE TITLE
Change font/font size

### ISSUE THREAD

**Issue by mkuprianowicz** [BalestraPatrick/ValueStepper#19]
Hi,
I would like to change font(and size) of valueLabel, but it is private. Maybe you can add property to change font also?

**Comment by BalestraPatrick** [comment]
Hey, that's a good idea! You're welcome to open a PR if you want, otherwise let me know and I'll work on it as soon as I have time 😄

**Comment by BalestraPatrick** [comment]
Just made the `valueLabel` property `public` as requested in the new version 1.3. Let me know if that is fine for you!

**Comment by sourabhsharmait** [comment]
Not able to change the font size of value label. Please make it designable.
