### ISSUE TITLE
Build Error - Shared is unavailable

### ISSUE THREAD

**Issue by hsmith825** [BalestraPatrick/ValueStepper#20]
I installed using Pod as indicated.  Made no changes and instantly had the error.  "Shared" is unavailable.  Use New Controller based solution.

Using Xcode 8.3.3.  Thanks for your help!
Howard

**Comment by BalestraPatrick** [comment]
Hey there, which branch are you specifying in your `Podfile`? Can you please share the code that it's causing the error?

**Comment by hsmith825** [comment]
Hi,

I Installed ValueStepper 1.3.

Thanks!!!
Howard

**Comment by BalestraPatrick** [comment]
@hsmith825 Were you able to fix the problem? If not, can you please share some code or a sample project please?

**Comment by hsmith825** [comment]
Hi Patrick,

I did not have a chance to code.  The problem occurred right after Iintalled the pod.  (pod ValueStepper).  the version installed is 1.3.  I am now using GMStepper with the same process and know problems.  Sorry their is nothing to send since I could not get started.

Thanks!
Howard
