### ISSUE TITLE
No number appears in the center label

### ISSUE THREAD

**Issue by nick-iCars** [BalestraPatrick/ValueStepper#24]
Not sure what broke but the number in the middle is no longer appearing in the app. I'm about to dive in and see if I can see what is going on.

**Comment by nick-iCars** [comment]
oh looks like the label is there but it's white on white. The tint of the edge is purple. The center label used to be purple too.

**Comment by BalestraPatrick** [comment]
We didn't ship any new update for a while now. Is it something related to you specific configuration of the component or the library itself?

**Comment by nick-iCars** [comment]
Not sure what happened, I think you're right, sorry for the premature issue.

**Comment by BalestraPatrick** [comment]
No worries, let me know if I can help in any way.
