### ISSUE TITLE
Not able to get tag for Decrement Button.

### ISSUE THREAD

**Issue by dhavalbarot** [BalestraPatrick/ValueStepper#26]
/// - decrease: decrease button has tag 0.
/// - increase: increase button has tag 1.
private enum Button: Int {
    case decrease
    case increase
}

You can not set the tag value of an element to 0. Need to modify that logic in order to get elements by tag value correctly.

/// - decrease: decrease button has tag 1.
/// - increase: increase button has tag 2.
private enum Button: Int {
    case decrease = 1
    case increase = 2
}

**Comment by BalestraPatrick** [comment]
Hey @dhavalbarot, I don't seem to understand the problem exactly here? Can you please show a more meaningful example and/or share an example project?

**Comment by Dave181295** [comment]
how can we get notified if it was increment or decrement ?

**Comment by Dave181295** [comment]
he's right, both the decrement and increment button has the same tag == 0
