### ISSUE TITLE
Bug in labelPressed function 

### ISSUE THREAD

**Issue by savyasachi** [BalestraPatrick/ValueStepper#27]
There is a subtle bug in `labelPressed` function on line 360. The following line of code
`if newValue >= self.minimumValue || newValue <= self.maximumValue`
must be replaced by
`if newValue >= self.minimumValue && newValue <= self.maximumValue`

The || operator must be replaced by && operator.

**Comment by BalestraPatrick** [comment]
Hey @savyasachi! You are welcome to submit a PR :)
