### ISSUE TITLE
Don't return early from increase/decrease functions when auto repeat is enabled

### ISSUE THREAD

**Issue by gcox** [BalestraPatrick/ValueStepper#5]
The `return` statement on lines [255](https://github.com/BalestraPatrick/ValueStepper/blob/master/Pod/Classes/ValueStepper.swift#L255) and [265](https://github.com/BalestraPatrick/ValueStepper/blob/master/Pod/Classes/ValueStepper.swift#L265) prevent a normal tap from changing the value and forces the user to tap+hold to change the value when autorepeat is enabled. Removing these two lines will cause the control to behave like the standard UIStepper where a tap+release will change the value by the step amount exactly once and a tap+hold will still autorepeat the value change.

**Comment by BalestraPatrick** [comment]
Thanks for the bug report, just fixed it!

**Comment by gcox** [comment]
Awesome, thanks!
